# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md
AllCops:
  TargetRubyVersion: 2.4
  Include:
    - lib/**/*.rb
    - test/**/*.rb
    - Gemfile
    - roda-oauth.gemspec
    - examples/**/*.rb
  Exclude:
    - Rakefile
    - test/rails_app/db/**/*.rb
    - lib/generators/**/*.rb
    - .bundle/**/*
    - vendor/**/*
    - test/tmp/**/*

Naming/FileName:
  Exclude:
    - Rakefile
    - Gemfile

Metrics/ModuleLength:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Metrics/ClassLength:
  Max: 1500

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false

# TO BE WORKED ON§
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
